#!/usr/bin/env node
// Generates service-worker.js with a precache list of every app file and a content hash as version.
const fs = require('fs'), path = require('path'), crypto = require('crypto');
const root = path.join(__dirname, '..');
function walk(dir) { return fs.readdirSync(path.join(root, dir)).flatMap(f => { const p = path.join(dir, f); return fs.statSync(path.join(root, p)).isDirectory() ? walk(p) : [p]; }); }
const files = ['index.html', 'styles.css', 'app.js', 'manifest.json']
  .concat(walk('modules'), walk('data').filter(f => f.endsWith('.js')), walk('assets'))
  .map(f => f.split(path.sep).join('/'));
const hash = crypto.createHash('sha256');
files.forEach(f => hash.update(f).update(fs.readFileSync(path.join(root, f))));
const version = hash.digest('hex').slice(0, 12);
const sw = `/* Generated by tools/build-sw.cjs — offline cache for the study platform. */
const VERSION = 'ifl-${version}';
const PRECACHE = ${JSON.stringify(['./'].concat(files), null, 1)};
self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  // Textbook PDF: network only (large, optional, not cached).
  if (/\\.pdf$/i.test(new URL(req.url).pathname)) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => {
    const net = fetch(req).then(res => {
      if (res && res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); }
      return res;
    }).catch(() => hit || (req.mode === 'navigate' ? caches.match('./index.html') : undefined));
    return hit || net;
  }));
});
`;
fs.writeFileSync(path.join(root, 'service-worker.js'), sw);
console.log('service-worker.js', files.length, 'files, version', version);
