#!/usr/bin/env python3
"""Build data/glossary.js from paraphrased definitions of the book's Glossary (printed pp. 485-496).
Definitions below are written in our own words; the script only looks up the glossary page on which
each term appears (when the extracted page text is available locally) so the app can cite it."""
import json, os, re, unicodedata
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = os.path.join(ROOT, 'source', 'extraction-notes', 'pages')
OFFSET = 28

# term, category, definition (paraphrased), related topic id (optional), lookup key used to locate the page
G = [
 ("Ahadith", "Sources & jurisprudence", "Plural of Hadith: reports of the Prophet's (pbuh) sayings and actions, and of Companions' actions he tacitly approved.", "t2.4", "Ah"),
 ("‘Ahd", "Contracts", "An undertaking — usually a unilateral promise, sometimes a bilateral obligation.", "t5.6", "‘Ahd"),
 ("‘Ain", "Money & property", "Determinate property (not a debt); tangible goods valued in themselves. Plural ‘Aayan.", "t3.2.1", "‘Ain:"),
 ("Ajr al-Mithl", "Leasing & services", "Rent or wage fixed by a judge or arbitrator (the customary rate) rather than by the parties.", "t11.2", "Ajr al-Mithl"),
 ("Ajr al-Musammah", "Leasing & services", "Rent or wage agreed by the parties in an Ijarah or Ujrah contract.", "t11.2", "Ajr al-Musammah"),
 ("Akhlaq", "Ethics", "Moral self-discipline governing one's conduct towards others.", "t2.2", "Akhl"),
 ("Al-Ajr", "Leasing & services", "A fee, commission or wage for services rendered or work done.", "t11.1", "Al-Ajr"),
 ("Al Ghunm bil Ghurm", "Principles", "Maxim: gain is justified only by bearing risk and engaging in the venture — the rationale for profit sharing in Shirkah.", "t4.3", "Ghunm"),
 ("Al-Hisbah", "Ethics", "Ombudsman-type institution that polices market imbalances to restore fair, market-based exchange.", "t2.5", "Hisbah"),
 ("Al Kali bil Kali", "Prohibitions", "Exchange in which both counter-values are deferred — the sale of a debt for a debt (Bai‘ al-Dayn bid-Dayn).", "t5.5.5", "K¯ali bil"),
 ("Al-Sarf", "Money & exchange", "Exchange of monetary value for monetary value (currency exchange); both prices must be settled simultaneously.", "t6.9", "Al-Sarf"),
 ("Al-Wadi‘ah", "Banking", "Safe-keeping of deposits as a trust on which no profit can be sought.", "t8.5.1", "Al-Wadi"),
 ("Amanah", "Banking", "Property held in trust; the trustee is not liable for loss unless he breaches his duty. If the bank is authorised to use current-account funds, the trust becomes a loan repayable in full.", "t8.5.1", "Am¯anah: Refers"),
 ("Ameen", "Contracts", "A trustee who safeguards another's property as his own and is not liable for damage without negligence.", "t11.2", "Ameen"),
 ("Aqaid", "Sources & jurisprudence", "Matters of belief and worship concerning the relationship between man and God.", "t2.2", "Aq¯aid"),
 ("‘Aqd", "Contracts", "Literally a tie or conjunction; legally, a contract.", "t5.2", "‘Aqd:"),
 ("‘Aqd Batil", "Contracts", "A void contract — defective in offer and acceptance, subject matter, consideration or delivery, or tainted by Riba, Gharar or Qimar.", "t5.7", "Aqd Batil"),
 ("‘Aqd Ghair Lazim", "Contracts", "A non-binding contract that either party may revoke without the other's consent.", "t5.7", "Ghair L¯azim"),
 ("‘Aqd Lazim", "Contracts", "A binding contract that no party can revoke unilaterally.", "t5.7", "Aqd L¯azim"),
 ("‘Aqilah", "Takaful & social", "Kinsmen who share a responsibility, historically the payment of blood money — a precedent for Takaful.", "t16.3", "Aqilah: Kin"),
 ("‘Arbun", "Contracts", "Down-payment taken after a sale is agreed; the seller may keep it if the buyer backs out.", "t6.10", "Arb¯un: Down"),
 ("‘Ariyah", "Contracts", "Gratuitous loan of a non-consumable object — a gift of its usufruct; the same item must be returned (unlike Qard).", "t7.5", "Ariyah"),
 ("Athman", "Money & exchange", "Plural of Thaman: monetary units used to pay prices and liabilities.", "t3.2.2", "Athman"),
 ("Bai‘ al ‘Arbun", "Contracts", "Sale with a down-payment that becomes part of the price if the buyer completes and is forfeited if he does not.", "t6.10", "al‘Arb"),
 ("Bai‘ al Dayn", "Prohibitions", "Sale of a debt or debt instrument; at a discount it is rejected by the majority of jurists.", "t5.5.5", "Bai‘ al Dayn"),
 ("Bai‘ al-Ghaib", "Prohibitions", "Sale of absent or concealed goods whose features are unknown.", "t5.5", "Gh¯aib"),
 ("Bai‘ al Hasat", "Prohibitions", "Pre-Islamic sale in which the object is determined by where a thrown pebble falls — prohibited for Gharar.", "t3.3.3", "Hasat"),
 ("Bai‘ al ‘Inah", "Prohibitions", "Sale and buy-back: an item is sold for cash and bought back at a higher credit price (or vice versa), producing a loan with interest — prohibited.", "t6.11", "‘Inah: Double"),
 ("Bai‘ al Khiyar", "Contracts", "Sale in which one party has an option to rescind within a set time.", "t5.8", "Bai‘ al Khiyar"),
 ("Bai‘ al-Majhul", "Prohibitions", "Sale in which the object, price or payment time is unknown.", "t5.5", "Majh¯ul"),
 ("Bai‘ al Mu‘allaq", "Contracts", "Suspended sale whose effect depends on a future condition or event.", "t5.7", "Mu‘allaq"),
 ("Bai‘ al Sarf", "Money & exchange", "Sale of gold, silver or monetary units against each other; must be spot, and equal where of the same kind.", "t6.9", "Bai‘ al Sarf"),
 ("Bai‘ Batil", "Contracts", "Void sale with no legal effect on the parties' rights and liabilities.", "t5.7", "Bai‘ Batil"),
 ("Bai‘ bil Wafa", "Contracts", "Sale with the seller's right to redeem by refunding the price — in substance a pledge; impermissible if resale is made a condition of the sale.", "t6.12", "Wafa"),
 ("Bai‘ Mu’ajjal", "Financing modes", "Credit sale: the price is paid later in a lump sum or instalments and is usually higher than the spot price.", "t6.5", "Mu´ajjal"),
 ("Bai‘ Murabaha", "Financing modes", "Sale at disclosed cost plus an agreed profit.", "t7.1", "Bai‘ Murabaha"),
 ("Bai‘ Musawamah", "Financing modes", "Sale by bargaining on price without disclosing the seller's cost.", "t6.7", "Bai‘ Musawamah"),
 ("Bai‘ Salam", "Financing modes", "Forward sale with full advance payment for specified goods delivered on a fixed future date — an exception allowed by the Prophet (pbuh); not for gold, silver or currencies.", "t10.1", "Bai‘ Salam"),
 ("Bai‘ Tawliyah", "Contracts", "Sale at cost price, e.g. to accommodate another.", "t6.7", "Tawliyah"),
 ("Bai‘ Wadhi‘ah", "Contracts", "Sale at a loss (below cost price).", "t6.7", "Wadhi‘ah: Sale"),
 ("Bai‘ wal Salaf", "Prohibitions", "Invalid combination of a sale with a loan as a condition of each other.", "t5.5.6", "wal Salaf"),
 ("Barnamaj", "Contracts", "Catalogue or list of the contents of a consignment.", "t5.4", "Barn"),
 ("Bayt al Mal", "Takaful & social", "The public treasury of an Islamic state.", "t2.5", "Bayt al"),
 ("Buyoo‘ al Amanat", "Contracts", "Trust-based (fiduciary) sales in which cost is disclosed: Murabaha, Tawliyah and Wadhi‘ah.", "t6.7", "Buyoo"),
 ("Dayn", "Money & property", "A debt — a liability arising from a credit transaction such as a credit sale or due rent.", "t7.2", "Dayn: Debt"),
 ("Dhaman", "Contracts", "Liability or responsibility; a guarantee; the entrepreneur's responsibility for the business.", "t5.7.3", "Dham¯an:\nTaking"),
 ("Dhaman Khatr al-Tariq", "Takaful & social", "Mutual pool from which traders' losses from road hazards were compensated.", "t16.3", "Khatr al-Tariq"),
 ("Dinar", "Money & exchange", "Historical gold coin currency.", "t3.2.2", "Dinar:"),
 ("Dirham", "Money & exchange", "Historical silver coin currency.", "t3.2.2", "Dirham:"),
 ("Falah", "Principles", "Success and welfare in this world and the Hereafter, presupposing faith and Shari’ah-conforming conduct.", "t2.3", "Falah:"),
 ("Fasid", "Contracts", "A defective (voidable) contract under Hanafi law because a condition of validity is missing.", "t5.7", "F¯asid"),
 ("Fatwah", "Sources & jurisprudence", "A religious ruling or edict (plural Fatawa).", "t2.4", "Fatwah:"),
 ("Fiqh", "Sources & jurisprudence", "Islamic jurisprudence — the science of deriving Shari’ah rulings.", "t2.4", "Fiqh:"),
 ("Fraidh", "Sources & jurisprudence", "Obligatory acts for Muslims.", "t2.2", "Fr¯aidh"),
 ("Fuduli", "Contracts", "Someone who contracts for another without being guardian or agent, or who exceeds his agency limits.", "t13.2", "Fuduli:"),
 ("Fulus", "Money & exchange", "Coins of base metals.", "t3.2.2", "Fulus"),
 ("Ghaban", "Prohibitions", "Defrauding others about goods' specifications or prices.", "t2.5", "Ghaban: Mis"),
 ("Ghaban-e-Fahish", "Prohibitions", "Gross overcharging by deception, implying the market price is charged; gives the buyer an option to revoke.", "t5.8", "Ghaban-e-Fahish"),
 ("Gharar", "Prohibitions", "Excessive uncertainty or hazard about a contract's essential elements (subject matter, price, delivery), causing undue loss to one party — e.g. selling what cannot be delivered or unknown contents.", "t3.3", "Gharar: Literally"),
 ("Gharmeen", "Takaful & social", "A Zakat category: those burdened by debts, including sureties who paid others' debts.", "t2.5", "Gh¯armeen"),
 ("Ghasib", "Contracts", "A usurper of another's property.", "t12.4.2", "Gh¯asib"),
 ("Habal-al-Hablah", "Prohibitions", "Sale of the unborn offspring of an animal — prohibited for Gharar.", "t3.3.3", "Habal"),
 ("Halal", "Principles", "Whatever the Shari’ah permits.", "t2.3", "Halal:"),
 ("Hamish Jiddiyah", "Financing modes", "Security deposit showing a promisor's serious intent; on breach the promisee recovers only actual loss from it.", "t5.6.1", "Hamish"),
 ("Haram", "Principles", "Whatever the Shari’ah prohibits.", "t2.3", "Haram:"),
 ("Hawalah", "Contracts", "Assignment of debt: responsibility for a debt is transferred to another; also the instrument (bill, cheque, draft) used.", "t7.8", "Hawalah:"),
 ("Hibah", "Contracts", "Gift: transfer of ownership without consideration.", "t8.5.1", "Hibah:"),
 ("Hilah (Hiyal)", "Prohibitions", "Legal devices or ruses used to circumvent a prohibition.", "t5.5.5", "Hilah"),
 ("Hukmi Qabza", "Contracts", "Constructive possession: the goods are under the buyer's risk and control without physical delivery.", "t5.4.2", "Hukmi"),
 ("Husnal Qadha", "Contracts", "Gracious repayment of a loan with a voluntary extra not stipulated in advance — individual discretion, not a system.", "t7.5", "Husnal"),
 ("Ibadat", "Sources & jurisprudence", "Acts of worship.", "t2.2", "Ib¯ad¯at"),
 ("Ibahatul Asliyah", "Principles", "Presumption of permissibility: economic activities not prohibited by the Qur’an and Sunnah are allowed.", "t17.4.3", "Asliyah"),
 ("Ijab", "Contracts", "Offer in a contract (paired with Qabul, acceptance).", "t5.4", "Ijab:"),
 ("Ijarah", "Financing modes", "Lease: sale of a defined usufruct for a defined period against known rent; only non-consumable assets can be leased because the lessor must bear ownership risk.", "t11.1", "Ijarah: Letting"),
 ("Ijarah Mosufah bil Zimmah", "Financing modes", "Lease of a described service or benefit without identifying specific units; a destroyed unit is replaced and the lease continues.", "t11.3.1", "Mosufah"),
 ("Ijarah Muntahia-bi-Tamleek", "Financing modes", "Lease ending in ownership transfer to the lessee, with lease and sale/gift kept as separate transactions.", "t11.5", "Muntahia-bi-Tamleek: Lease"),
 ("Ijarah-wal-Iqtina‘", "Financing modes", "Islamic hire-purchase style lease with a separate unilateral undertaking to transfer ownership; Ijarah rules fully apply.", "t11.5", "Iqtina‘: A mode"),
 ("Ijma‘a", "Sources & jurisprudence", "Consensus of qualified scholars on a Shari’ah matter; consensus of the Companions carries special weight.", "t2.4", "Ijma‘a:"),
 ("Ijtihad", "Sources & jurisprudence", "A qualified jurist's effort to derive rulings where texts are not explicit; no Ijtihad against express injunctions.", "t2.4", "Ijtihad:"),
 ("‘Illah", "Sources & jurisprudence", "The effective cause of a ruling, used for analogy — e.g. the cause of Riba rules in exchanges.", "t3.2.1", "‘Illah:"),
 ("Imam", "Sources & jurisprudence", "Leader, guide or ruler.", None, "Imam:"),
 ("Iman", "Principles", "Faith.", "t2.2", "Iman:"),
 ("‘Inan", "Partnership", "General partnership in which each partner contributes capital and may work, not necessarily equally.", "t12.2.2", "In¯an (a type"),
 ("Israf", "Ethics", "Extravagance — excessive or unnecessary spending even on permissible things.", "t2.5", "Isr¯af"),
 ("Istihsan", "Sources & jurisprudence", "Juristic preference allowing an exception to strict analogy when human welfare demands.", "t2.4", "Istihsan"),
 ("Istijar", "Leasing & services", "Hiring or renting — another term for Ijarah.", "t11.1", "Istij¯ar"),
 ("Istijrar", "Contracts", "Repeat or continuous supply sale at agreed prices and payment terms.", "t13.5", "Istijrar:"),
 ("Istisna‘a", "Financing modes", "Order to manufacture or construct, with advance, deferred or instalment payment and future delivery.", "t10.6", "Istisna‘a: Order"),
 ("‘Iwad", "Principles", "Equivalent counter-value in an exchange; its absence makes an increase Riba.", "t3.2.1", "‘Iwad"),
 ("Jahl / Jahala", "Prohibitions", "Ignorance or indefiniteness about the parties, their obligations, the subject matter or price — a source of Gharar.", "t3.3", "Jahala"),
 ("Ju‘alah", "Contracts", "Reward for achieving a specified result that is not certain to be achieved; the reward is earned only on the result.", "t13.4", "Ji‘alah"),
 ("Kafalah", "Contracts", "Suretyship/guarantee: a third party undertakes to the creditor that the debtor's obligation will be paid.", "t5.7.3", "Kafalah:"),
 ("Khalabah", "Prohibitions", "Misleading marketing that exaggerates a product's quality to naive buyers.", "t2.5", "Khalabah"),
 ("Kharaj bil Daman", "Principles", "Maxim: entitlement to gain goes with liability for loss.", "t4.3", "Kharaj bi-al-Daman"),
 ("Khatar", "Prohibitions", "A form of Gharar where a party's liability is contingent, delivery is beyond control, or payment is uncertain.", "t16.2.1", "Khatar:"),
 ("Khiyar", "Options (Khiyar)", "An option or right to annul a contract.", "t5.8", "Khiy¯ar:"),
 ("Khiyar al ‘Aib", "Options (Khiyar)", "Option of defect: the buyer may return defective goods.", "t5.8", "Khiyar al ‘Aib"),
 ("Khiyar al-Majlis", "Options (Khiyar)", "Option of the session: either party may annul before they separate.", "t5.8", "Majlis"),
 ("Khiyar al Ro’yat", "Options (Khiyar)", "Option of inspection: the buyer may revoke on seeing goods bought unseen.", "t5.8", "Ro’yat"),
 ("Khiyar al-Shart", "Options (Khiyar)", "Stipulated option allowing a party to cancel within an agreed period.", "t5.8", "Khiyar al-Shart"),
 ("Khiyar al Wasf", "Options (Khiyar)", "Option of description: the buyer may return goods not matching the described attributes.", "t5.8", "Khiyar al Wasf"),
 ("Khiyar-e-Ghaban", "Options (Khiyar)", "Option for gross overpricing where the buyer was led to believe he paid the market price.", "t5.8", "Khiyar-e-Ghaban"),
 ("Khiyar-e-Naqad", "Options (Khiyar)", "Option of payment: the sale is annulled if payment is not made within an agreed short period.", "t5.8", "Naqad"),
 ("Ma‘lum", "Contracts", "Known to the parties.", "t5.4", "Ma‘lum"),
 ("Mabi‘", "Contracts", "The subject matter of a sale.", "t5.4", "Mabi‘"),
 ("Maisir", "Prohibitions", "Gambling — acquiring wealth by chance without counter-value, work or liability; named after an ancient Arabian arrow game.", "t3.3.1", "Maisir:"),
 ("Mal", "Money & property", "Anything capable of possession — money, commodities, real estate.", "t5.4", "M¯al: Anything"),
 ("Mal-e-Mutaqawam", "Money & property", "Wealth lawful to use and of commercial value under Shari’ah (legal tender included; wine and pork excluded for Muslims).", "t5.4", "Mutaqawam"),
 ("Maslaha-e-Mursalah", "Sources & jurisprudence", "Public welfare considered by jurists in Ijtihad when resolving new issues.", "t2.4", "Mursalah"),
 ("Mawalat", "Takaful & social", "Pre-Islamic contract where one party bequeathed property to another who undertook to pay his blood money.", "t16.3", "Maw¯al¯at"),
 ("Mawquf", "Contracts", "A contract whose effect is suspended pending an event or ratification.", "t5.7", "Mawquf:"),
 ("Mithaq", "Contracts", "A solemn covenant with greater sanctity than an ordinary contract.", "t5.2", "Mith¯aq"),
 ("Mithlan bi-mithlin", "Money & exchange", "‘Like for like’ — equality required when exchanging Ribawi goods of one kind.", "t3.2.1", "Mithlam"),
 ("Mithli", "Money & property", "Fungible goods whose units are identical and returnable in kind (gold, wheat, currencies).", "t3.2.1", "Mithli:"),
 ("Mu‘amalat", "Sources & jurisprudence", "Economic and transactional dealings between people.", "t2.2", "Mu‘¯amal¯at"),
 ("Mua‘awamah", "Prohibitions", "Sale of a tree's fruit for years ahead without specifying quantity, price or delivery — prohibited.", "t3.3.3", "Mua‘awamah"),
 ("Mubah", "Principles", "Lawful — permissible to use or trade.", "t2.3", "Mub¯ah"),
 ("Mudarabah", "Partnership", "Partnership where one party provides capital and the other management; profit shared as agreed, loss borne by the capital provider.", "t12.4", "Mudarabah: A form"),
 ("Mudarib", "Partnership", "The managing/entrepreneur partner in a Mudarabah.", "t12.4", "Mudarib:"),
 ("Muflis", "Contracts", "An insolvent or bankrupt debtor.", "t7.15", "Muflis"),
 ("Mugharasah", "Partnership", "Joint plantation project sharing the produce.", "t15.3.4", "Mugh¯arasah"),
 ("Mulamasah", "Prohibitions", "Sale concluded by touching the item or its package without knowing its details — prohibited.", "t3.3.3", "Mulamasah"),
 ("Munabadhah", "Prohibitions", "Sale by throwing garments to each other without examining them — prohibited.", "t3.3.3", "Munabadhah"),
 ("Murabaha", "Financing modes", "Sale in which the seller discloses cost and adds an agreed profit; used by banks on a client's purchase request (Murabaha to Purchase Orderer).", "t7.1", "Murabaha: Literally"),
 ("Musaqah", "Partnership", "Contract sharing a garden's produce with someone who irrigates and tends it.", "t15.3.4", "Mus¯aqah:"),
 ("Musawamah", "Financing modes", "Ordinary bargained sale without reference to the seller's cost.", "t6.7", "Musawamah: A general"),
 ("Musharakah", "Partnership", "Partnership in which all partners contribute capital; profit by agreed ratio, loss by capital; may be permanent or diminishing.", "t12.3", "Musharakah: Partnership"),
 ("Mustarsal", "Prohibitions", "An inexperienced market entrant unaware of prices, who must not be exploited.", "t5.8", "Mustarsal"),
 ("Muzara‘ah", "Partnership", "Share-cropping: one party tills another's land for a share of the produce.", "t15.3.4", "Muzara"),
 ("Najash", "Prohibitions", "Bidding up a price without intending to buy.", "t2.5", "Najash"),
 ("Nass", "Sources & jurisprudence", "The clear texts of the Qur’an and Sunnah.", "t2.4", "Nass:"),
 ("Nawahi", "Sources & jurisprudence", "Acts prohibited by Islam.", "t2.2", "Naw¯ahi"),
 ("Niyyah", "Principles", "Intention behind an act.", "t15.3.4", "Niyyah"),
 ("Qabul", "Contracts", "Acceptance in a contract (paired with Ijab, offer).", "t5.4", "Qabul:"),
 ("Qard", "Contracts", "Loan of something of value to be repaid in the same or similar amount; repayment is obligatory and no benefit may be stipulated.", "t7.5", "Qard: Literally"),
 ("Qard al Hasan", "Contracts", "A benevolent loan repaid without any increase; in Islamic law every loan must be of this kind.", "t7.5", "Qard al Hasan:"),
 ("Qimar", "Prohibitions", "Gambling: ownership depends on an uncertain event so one party gains at the other's loss.", "t3.3.1", "Qim¯ar:"),
 ("Qirad", "Partnership", "Another name for Mudarabah (also Muqaradah).", "t12.4", "Qir¯ad: Another"),
 ("Qirad mithl", "Partnership", "Market-rate compensation paid to a Mudarib if the Mudarabah becomes defective.", "t12.4", "Qir¯ad mithl"),
 ("Qirsh", "Money & exchange", "A base-metal coin once used in Iraq.", None, "Qirsh"),
 ("Qisas", "Sources & jurisprudence", "Legal retribution for harm to human life.", None, "Qis¯as"),
 ("Qiyami / Qimi", "Money & property", "Non-fungible goods whose units differ in value.", "t3.2.1", "Qiyami"),
 ("Qiyas", "Sources & jurisprudence", "Analogy: extending a ruling to a new case sharing the same ‘Illah.", "t2.4", "Qiy¯as:"),
 ("Ra’asul-mal", "Money & property", "Principal of a loan or debt, or capital invested in a business.", "t12.4.1", "Ra’asul"),
 ("Ra‘iee", "Ethics", "A person in charge who is responsible for those under him.", None, "R¯a‘iee"),
 ("Rabbul-mal", "Partnership", "The capital provider in Shirkah/Mudarabah.", "t12.4", "Rabbul-m¯al:"),
 ("Riba", "Prohibitions", "Any increase over the principal of a loan or debt, or excess in exchange of like goods, gained without an equivalent counter-value.", "t3.2", "Riba: Literally"),
 ("Riba al-Fadl", "Prohibitions", "Excess in a hand-to-hand exchange of the same Ribawi genus (e.g. more dates for fewer better dates).", "t3.2.1", "Riba Al-Fadl"),
 ("Riba al-Nasiah", "Prohibitions", "Riba of delay: increase on a loan or debt for time, or deferment in exchanging Ribawi goods; modern bank interest falls here.", "t3.2.1", "Riba Al-Nasiah"),
 ("Ribawi", "Money & exchange", "Goods subject to Riba rules in exchange: monetary units and items sold by weight or measure (gold, silver, currencies, wheat, dates, salt).", "t3.2.1", "Ribawi:"),
 ("Ribh al-mithl", "Financing modes", "A comparable (matching) rate of profit.", None, "Ribh-al-mithl"),
 ("Rahn", "Contracts", "Pledge or collateral that the creditor may sell to recover an unpaid debt.", "t7.7", "Rihn or Rahn"),
 ("Rukban", "Ethics", "Rural traders bringing goods to town, whom middlemen were forbidden to intercept.", "t2.5", "Rukb¯an"),
 ("Sa‘a", "Money & exchange", "A historical volume measure for grain.", None, "S¯a‘a"),
 ("Sadd al-Zarai‘", "Sources & jurisprudence", "Blocking the means: prohibiting a transaction that leads to an illicit end.", "t2.4", "Sadd al-Zar"),
 ("Sahabah", "Sources & jurisprudence", "The Companions of the Prophet (pbuh).", None, "Sah¯abah"),
 ("Salaf", "Contracts", "(i) A loan for a fixed term yielding no profit, or another name for Salam; (ii) early generations of scholars.", "t10.1", "Salaf: Used"),
 ("Sanadat", "Capital markets", "Investment certificates — another name for Sukuk.", "t15.3", "Sanad"),
 ("Sarf", "Money & exchange", "Contract exchanging gold, silver or monetary units.", "t6.9", "Sarf: Contract"),
 ("Sawa’an bi-sawa’in", "Money & exchange", "‘Equal for equal’ in exchanges of like Ribawi goods.", "t3.2.1", "Saw´"),
 ("Shari’ah", "Sources & jurisprudence", "Divine guidance in the Qur’an and Sunnah covering belief and practice.", "t2.4", "Shar¯ı´ah: Divine"),
 ("Shart-e-Jazai", "Financing modes", "Clause in Istisna‘a reducing the price for late delivery — the reduction benefits the buyer, unlike payment-default penalties that go to charity.", "t10.8", "Jaz¯ai"),
 ("Shirkah", "Partnership", "Commingling of money, work or obligations to earn profit or appreciation and share loss by ownership; includes Musharakah and Mudarabah.", "t12.2", "Shirkah: Commingling"),
 ("Shirkatul‘aqd", "Partnership", "Contractual business partnership formed to earn profit.", "t12.2.2", "Shirkatul‘aqd:"),
 ("Shirkatulmilk", "Partnership", "Partnership in ownership (joint ownership), not formed for business.", "t12.2.1", "Shirkatulmilk:"),
 ("Shuf‘ah", "Contracts", "Pre-emption right of a co-owner or neighbour when landed property is sold.", None, "Shuf"),
 ("Suftajah", "Banking", "Historical instrument for transferring money: funds deposited in one place for payment elsewhere.", "t14.6", "Suftajah"),
 ("Sukuk", "Capital markets", "Certificates of equal value representing undivided ownership in tangible assets, usufruct, services, or specific projects or investment activities.", "t15.3", "Sukuk: Certificates"),
 ("Sunnah", "Sources & jurisprudence", "The Prophet's (pbuh) sayings, actions and tacit approvals as reported in Hadith.", "t2.4", "Sunnah: Literally"),
 ("Ta‘zir", "Sources & jurisprudence", "Discretionary punishments not fixed by the texts, set by a judge.", None, "T‘azir"),
 ("Ta‘liq", "Contracts", "A condition suspending a contract on a future event.", "t5.7", "T‘aliq"),
 ("Ta’mein", "Takaful & social", "Arabic term for insurance (reassurance, guarantee).", "t16.3", "Ta’mein"),
 ("Tabarru‘", "Takaful & social", "A gratuitous benefit given without return — basis of Takaful contributions; voluntary extra repayment of a loan is Tabarru‘ only if never stipulated or systematised.", "t16.3", "Tabarru‘: Benefits"),
 ("Tabzir", "Ethics", "Spending on explicitly prohibited things, whatever the amount.", "t2.5", "Tabzir"),
 ("Takaful", "Takaful & social", "Islamic cooperative insurance based on mutual help (Ta‘awun) and joint risk-sharing among participants.", "t16.3", "Takaful: A form"),
 ("Taqwa", "Ethics", "God-consciousness and righteousness, including care for fellow humans.", "t2.2", "Taqwa"),
 ("Tawarruq", "Financing modes", "Buying on credit and selling at spot to a third party to obtain cash.", "t13.3", "Tawarruq: Acquiring"),
 ("Thaman", "Money & exchange", "Price; the monetary counter-value in an exchange.", "t5.4", "Thaman:"),
 ("Thaman-e-mithl", "Money & exchange", "Normal market price used when the actual price is in dispute.", None, "Thaman-e-mithl"),
 ("Ujrah", "Leasing & services", "Wage or fee for services (Ijarah of services); requires acceptance by a specified worker, unlike Ju‘alah.", "t13.4.3", "Ujrah: Wages"),
 ("Ujratul-mithl", "Leasing & services", "Market-rate remuneration payable when the underlying contract becomes defective.", "t12.4", "Ujratul-mithl"),
 ("Uqood-e-Mu‘awadha", "Contracts", "Commutative (exchange) contracts in which a return may be earned: sale, Ijarah, paid Wakalah.", "t5.3", "Mu‘awadha: Commutative"),
 ("Uqood Ghair Mu‘awadha", "Contracts", "Non-commutative contracts earning no return: loan, gift, guarantee, assignment of debt.", "t5.3", "Ghair Mu‘awadha"),
 ("Wa‘d", "Contracts", "A promise; it does not itself create contractual rights and may be binding or non-binding.", "t5.6", "W‘adah"),
 ("Wadi‘ah", "Banking", "Deposit held in trust; the custodian is liable only for negligence, but if used with permission it becomes his liability.", "t8.5.1", "Wadi‘ah: Am"),
 ("Wakalah", "Contracts", "Agency contract, with or without fee.", "t13.2", "Wakalah: Contract"),
 ("Wakalatul Istismar", "Banking", "Investment agency: the manager earns a pre-agreed fee while investors take all profit or loss.", "t13.2.2", "Wakalatul Istism¯ar:"),
 ("Waqf", "Takaful & social", "Endowment: property dedicated to charitable or family beneficiaries that cannot be sold, inherited or gifted.", "t16.3", "Waqf: Retention"),
 ("Yadan bi-yadin", "Money & exchange", "‘Hand to hand’ — spot settlement required in exchanging Ribawi goods.", "t3.2.1", "Yadam"),
 ("Zakah", "Takaful & social", "Obligatory annual levy on wealth above Nisab, distributed to the eight Qur’anic categories (9:60) including the poor and needy.", "t2.5", "Zakah/Zakat"),
 ("Zulm", "Ethics", "Injustice — usurping others' rights or denying fair recompense.", "t2.3", "Zulm"),
]

# Topic links verified against data/chapters (term -> topic id)
TOPIC = {
 "Ahadith":"t2.2.1","‘Ahd":"t5.2.1","‘Ain":"t5.2","Akhlaq":"t2.2","Al Ghunm bil Ghurm":"t4.2.6","Al-Hisbah":"t2.5.5",
 "Al Kali bil Kali":"t6.10","Al-Sarf":"t3.2.1.d","Amanah":"t7.11","Aqaid":"t2.2","‘Aqd":"t5.2.1","‘Aqd Batil":"t5.7.3",
 "‘Arbun":"t6.9","‘Ariyah":"t7.2","Athman":"t4.7.1","Bai‘ al ‘Arbun":"t6.9","Bai‘ al Dayn":"t7.16","Bai‘ al-Ghaib":"t6.7",
 "Bai‘ al Hasat":"t6.7","Bai‘ al Khiyar":"t6.12","Bai‘ al-Majhul":"t6.7","Bai‘ al Mu‘allaq":"t5.9","Bai‘ al Sarf":"t3.2.1.d",
 "Bai‘ Batil":"t5.7.3","Bai‘ bil Wafa":"t6.8","Bai‘ Mu’ajjal":"t9.6.1","Bai‘ Murabaha":"t9.3","Bai‘ Musawamah":"t9.11",
 "Bai‘ Salam":"t10.2","Bai‘ Tawliyah":"t9.1","Bai‘ Wadhi‘ah":"t9.1","Bai‘ wal Salaf":"t5.5.5","Barnamaj":"t6.5.1",
 "Bayt al Mal":"t2.5.1","Buyoo‘ al Amanat":"t9.3","Dayn":"t7.2","Dhaman":"t7.15","Dinar":"t4.7.1","Dirham":"t4.7.1",
 "Falah":"t2.2.2","Fasid":"t5.7.2","Fatwah":"t2.2.1","Fiqh":"t2.2","Fraidh":"t2.2","Fulus":"t4.7.1","Ghaban":"t3.3.1",
 "Ghaban-e-Fahish":"t6.12","Gharar":"t3.2.2","Gharmeen":"t2.5.2","Habal-al-Hablah":"t6.7","Halal":"t2.2","Haram":"t2.2",
 "Hawalah":"t7.14","Hibah":"t5.8","Hilah (Hiyal)":"t6.11","Husnal Qadha":"t7.11","Ibadat":"t2.2","Ibahatul Asliyah":"t5.5",
 "Ijab":"t5.4.1","Ijma‘a":"t2.2.1","Ijtihad":"t2.2.1","‘Illah":"t3.2.1.d","Iman":"t2.2","Israf":"t2.5.4","Istihsan":"t2.2.1",
 "Istisna‘a":"t10.11","‘Iwad":"t3.2.1.e","Jahl / Jahala":"t3.2.2","Kafalah":"t7.15","Khalabah":"t3.3.1","Kharaj bil Daman":"t4.2.6",
 "Khiyar":"t6.12","Khiyar al ‘Aib":"t6.12","Khiyar al-Majlis":"t6.12","Khiyar al Ro’yat":"t6.12","Khiyar al-Shart":"t6.12",
 "Khiyar al Wasf":"t6.12","Khiyar-e-Ghaban":"t6.12","Khiyar-e-Naqad":"t6.12","Ma‘lum":"t5.4.2","Mabi‘":"t5.4.2","Maisir":"t3.2.3",
 "Mal":"t5.2","Mal-e-Mutaqawam":"t5.2","Maslaha-e-Mursalah":"t2.2.2","Mithaq":"t5.2.1","Mithlan bi-mithlin":"t3.2.1.d",
 "Mithli":"t3.2.1.d","Mu‘amalat":"t5.5","Mua‘awamah":"t6.7","Mubah":"t2.2","Muflis":"t7.13","Mulamasah":"t6.7","Munabadhah":"t6.7",
 "Murabaha":"t9.3","Musawamah":"t9.11","Mustarsal":"t3.3.4","Najash":"t3.3.1","Nass":"t2.2.1","Nawahi":"t2.2","Qabul":"t5.4.1",
 "Qard":"t7.2","Qard al Hasan":"t7.2","Qimar":"t3.2.3","Qiyami / Qimi":"t3.2.1.d","Qiyas":"t2.2.1","Ra’asul-mal":"t7.7",
 "Riba":"t3.2","Riba al-Fadl":"t3.2.1.d","Riba al-Nasiah":"t3.2.1","Ribawi":"t3.2.1.d","Rahn":"t7.15","Rukban":"t3.3.4",
 "Sadd al-Zarai‘":"t2.2.1","Salaf":"t7.2","Sarf":"t3.2.1.d","Sawa’an bi-sawa’in":"t3.2.1.d","Shari’ah":"t2.2","Shart-e-Jazai":"t10.11.4",
 "Sunnah":"t2.2.1","Ta‘liq":"t5.9","Tabzir":"t2.5.4","Taqwa":"t2.2","Thaman":"t6.5.2","Uqood-e-Mu‘awadha":"t5.8",
 "Uqood Ghair Mu‘awadha":"t5.8","Yadan bi-yadin":"t3.2.1.d","Zakah":"t2.5.2","Zulm":"t3.3.5","Bai‘ Mu’ajjal":"t9.6.1",
}
G = [(t, c, d, TOPIC.get(t, top), k) for (t, c, d, top, k) in G]

def norm(s):
    s = unicodedata.normalize('NFKD', s)
    return ''.join(c for c in s if not unicodedata.combining(c)).lower()

pages = {}
if os.path.isdir(PAGES):
    for p in range(513, 525):
        f = os.path.join(PAGES, 'p%03d.txt' % p)
        if os.path.exists(f):
            pages[p] = norm(open(f, encoding='utf-8').read())

out = []
for term, cat, d, topic, key in G:
    page = None
    k = norm(key)
    for p, txt in pages.items():
        if k in txt:
            page = p - OFFSET
            break
    e = {"term": term, "cat": cat, "def": d, "source": "Glossary"}
    if page: e["page"] = page
    if topic: e["topic"] = topic
    out.append(e)

missing = [e["term"] for e in out if "page" not in e]
js = "/* Glossary — definitions paraphrased from the textbook's Glossary (printed pp. 485–496).\n   Generated by tools/build_glossary.py. Chapter-level definitions are merged in at runtime. */\n"
js += "IFL_DATA.register('glossary', " + json.dumps(out, ensure_ascii=False, indent=0) + ");\n"
open(os.path.join(ROOT, 'data', 'glossary.js'), 'w', encoding='utf-8').write(js)
print(len(out), 'terms; no page found for:', missing)
