/* Generated by tools/build-sw.cjs — offline cache for the study platform. */
const VERSION = 'ifl-683f08d62958';
const PRECACHE = [
 "./",
 "index.html",
 "styles.css",
 "app.js",
 "manifest.json",
 "modules/calculators.js",
 "modules/components.js",
 "modules/progress.js",
 "modules/router.js",
 "modules/srs.js",
 "modules/store.js",
 "modules/timer.js",
 "modules/util.js",
 "modules/views/cases.js",
 "modules/views/compare.js",
 "modules/views/concept-map.js",
 "modules/views/dashboard.js",
 "modules/views/diagrams.js",
 "modules/views/exam.js",
 "modules/views/finder.js",
 "modules/views/flashcards.js",
 "modules/views/glossary.js",
 "modules/views/guided.js",
 "modules/views/learn.js",
 "modules/views/mock.js",
 "modules/views/personal.js",
 "modules/views/practice.js",
 "modules/views/quiz.js",
 "modules/views/search.js",
 "modules/views/settings.js",
 "modules/views/topic.js",
 "data/case-studies.js",
 "data/chapters/ch01.js",
 "data/chapters/ch02.js",
 "data/chapters/ch03.js",
 "data/chapters/ch04.js",
 "data/chapters/ch05.js",
 "data/chapters/ch06.js",
 "data/chapters/ch07.js",
 "data/chapters/ch08.js",
 "data/chapters/ch09.js",
 "data/chapters/ch10.js",
 "data/chapters/ch11.js",
 "data/chapters/ch12.js",
 "data/chapters/ch13.js",
 "data/chapters/ch14.js",
 "data/chapters/ch15.js",
 "data/chapters/ch16.js",
 "data/chapters/ch17.js",
 "data/chapters/ch18.js",
 "data/comparisons.js",
 "data/concepts.js",
 "data/course-index.js",
 "data/diagrams.js",
 "data/glossary.js",
 "data/mode-finder.js",
 "data/registry.js",
 "data/study-plans.js",
 "assets/icons/icon-192.png",
 "assets/icons/icon-512.png",
 "assets/icons/icon.svg"
];
self.addEventListener('install', e => {
  e.waitUntil(caches.open(VERSION).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k !== VERSION).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  // Textbook PDF: network only (large, optional, not cached).
  if (/\.pdf$/i.test(new URL(req.url).pathname)) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => {
    const net = fetch(req).then(res => {
      if (res && res.ok) { const copy = res.clone(); caches.open(VERSION).then(c => c.put(req, copy)); }
      return res;
    }).catch(() => hit || (req.mode === 'navigate' ? caches.match('./index.html') : undefined));
    return hit || net;
  }));
});
